# Generated by Django 4.2.20 on 2025-04-13 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_student_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='fee_status',
            field=models.CharField(default='unpaid', max_length=20),
        ),
        migrations.AddField(
            model_name='student',
            name='last_payment_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='transaction_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
