services:
  - type: web
    name: school-management
    env: python
    region: oregon
    buildCommand: |
      python manage.py makemigrations --noinput
      python manage.py migrate --noinput
      pip install --upgrade pip
      pip install -r requirements.txt
      python manage.py collectstatic --no-input
    startCommand: gunicorn school_management.wsgi:application --bind 0.0.0.0:$PORT
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: school_management.settings
      - key: SECRET_KEY
        value: ${SECRET_KEY}
      - key: DEBUG
        value: ${DEBUG}
      - key: ALLOWED_HOSTS
        value: "*"
      - key: EMAIL_HOST_USER
        value: ${EMAIL_HOST_USER}
      - key: EMAIL_HOST_PASSWORD
        value: ${EMAIL_HOST_PASSWORD}
      - key: DEFAULT_FROM_EMAIL
        value: ${DEFAULT_FROM_EMAIL}
      - key: ADMIN_EMAIL
        value: ${ADMIN_EMAIL}
      - key: RAZORPAY_KEY_ID
        value: ${RAZORPAY_KEY_ID}
      - key: RAZORPAY_KEY_SECRET
        value: ${RAZORPAY_KEY_SECRET}
      - key: RAZORPAY_CURRENCY
        value: ${RAZORPAY_CURRENCY}
      - key: DATABASE_URL
        value: ${DATABASE_URL}

    plan: free