# Generated by Django 5.1.7 on 2025-04-09 05:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('school_teachers', '0001_initial'),
        ('subjects', '0004_alter_studentmark_grade'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_name', models.CharField(choices=[('1', 'Class 1'), ('2', 'Class 2'), ('3', 'Class 3'), ('4', 'Class 4'), ('5', 'Class 5')], max_length=2)),
                ('day', models.CharField(choices=[('monday', 'Monday'), ('tuesday', 'Tuesday'), ('wednesday', 'Wednesday'), ('thursday', 'Thursday'), ('friday', 'Friday'), ('saturday', 'Saturday')], max_length=10)),
                ('period', models.CharField(choices=[('1', '1st Period'), ('2', '2nd Period'), ('3', '3rd Period'), ('4', '4th Period'), ('5', '5th Period'), ('6', '6th Period'), ('7', '7th Period'), ('8', '8th Period')], max_length=2)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('room_number', models.CharField(max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subjects.subject')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school_teachers.teacher')),
            ],
            options={
                'ordering': ['class_name', 'day', 'period'],
                'unique_together': {('class_name', 'day', 'period')},
            },
        ),
    ]
