# Generated by Django 5.1.7 on 2025-04-08 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0002_studentmark'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentmark',
            name='grade',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('F', 'F')], default='F', max_length=1),
        ),
        migrations.AlterField(
            model_name='studentmark',
            name='percentage',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
