# Generated by Django 5.1.7 on 2025-04-08 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0003_alter_studentmark_grade_alter_studentmark_percentage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentmark',
            name='grade',
            field=models.CharField(choices=[('A+', 'A+'), ('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E (Fail)')], default='E', max_length=2),
        ),
    ]
