# Generated by Django 4.2.20 on 2025-04-11 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_alter_attendance_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attendance',
            options={'ordering': ['-date', 'student__first_name']},
        ),
        migrations.RemoveField(
            model_name='attendancereport',
            name='created_by',
        ),
        migrations.AlterField(
            model_name='attendance',
            name='remarks',
            field=models.TextField(blank=True),
        ),
    ]
