# Generated by Django 4.2.20 on 2025-04-13 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0003_alter_attendance_options_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AttendanceReport',
        ),
    ]
