# Generated by Django 4.2.20 on 2025-04-13 18:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('students', '0003_student_fee_status_student_last_payment_date_and_more'),
        ('attendance', '0004_delete_attendancereport'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('class_name', models.CharField(blank=True, max_length=10, null=True)),
                ('total_students', models.IntegerField(default=0)),
                ('present_count', models.IntegerField(default=0)),
                ('absent_count', models.IntegerField(default=0)),
                ('late_count', models.IntegerField(default=0)),
                ('half_day_count', models.IntegerField(default=0)),
                ('present_percentage', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('absent_percentage', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('late_percentage', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('half_day_percentage', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('generated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='students.student')),
            ],
            options={
                'ordering': ['-date', 'class_name'],
            },
        ),
    ]
