# Generated by Django 4.2.20 on 2025-04-18 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0006_teacherattendance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='teacher',
        ),
        migrations.DeleteModel(
            name='TeacherAttendance',
        ),
    ]
